SELECT * FROM students;
SELECT * FROM STAFF;
SELECT * FROM SUBJECTS;
SELECT * FROM CLASSES;



SELECT id, first_name FROM students;

SELECT * FROM SUBJECTS WHERE subject_name = 'Mathematics';
SELECT * FROM STAFF_SALARY WHERE SALARY >= 10000;
SELECT * FROM STAFF_SALARY WHERE SALARY BETWEEN 6000 AND 10000 ORDER BY salary;
SELECT DISTINCT STAFF_TYPE FROM STAFF;
SELECT STAFF_ID, SALARY,
	CASE WHEN SALARY >= 10000 THEN 'HIGH SALARY'
		WHEN SALARY BETWEEN 5000 AND 10000 THEN 'AVERAGE SALARY'
		WHEN SALARY <5000 THEN 'LOW SALARY'
	END AS RANGE
FROM STAFF_SALARY;

--fetch all the class name where music is taught as subject.
SELECT *
FROM SUBJECTS SUB
JOIN CLASSES CLS ON SUB.SUBJECT_ID = CLS.SUBJECT_ID
WHERE SUBJECT_NAME = 'Music'

--fetch fullname of all staff who teach mathematics
SELECT DISTINCT (STF.FIRST_NAME || '' || STF.LAST_NAME) AS FULL_NAME
FROM SUBJECTS SUB
JOIN CLASSES CLS ON CLS.SUBJECT_ID = SUB.SUBJECT_ID
JOIN STAFF STF ON CLS.TEACHER_ID = STF.STAFF_ID
WHERE SUB.SUBJECT_NAME = 'Mathematics' 
	


